// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mobile_controller.proto
//
// NOTE: This file is generated during Docker build via buf.
// For local development, regenerate with:
//   cd proto && buf generate --template buf.gen.mobile.yaml

package mobile_controller

import (
	fmt "fmt"

	proto "google.golang.org/protobuf/proto"
)

// Ensure proto package is used.
var _ = proto.Marshal
var _ = fmt.Errorf

type RegisterPhoneRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RegisterPhoneRequest) Reset()         { *x = RegisterPhoneRequest{} }
func (x *RegisterPhoneRequest) String() string { return fmt.Sprintf("RegisterPhoneRequest{Name:%q}", x.Name) }
func (x *RegisterPhoneRequest) ProtoMessage()  {}

func (x *RegisterPhoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterPhoneResponse struct {
	Serial  string `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RegisterPhoneResponse) Reset()         { *x = RegisterPhoneResponse{} }
func (x *RegisterPhoneResponse) String() string { return fmt.Sprintf("RegisterPhoneResponse{Serial:%q}", x.Serial) }
func (x *RegisterPhoneResponse) ProtoMessage()  {}

func (x *RegisterPhoneResponse) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *RegisterPhoneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnregisterPhoneRequest struct {
	Serial string `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
}

func (x *UnregisterPhoneRequest) Reset()         { *x = UnregisterPhoneRequest{} }
func (x *UnregisterPhoneRequest) String() string { return fmt.Sprintf("UnregisterPhoneRequest{Serial:%q}", x.Serial) }
func (x *UnregisterPhoneRequest) ProtoMessage()  {}

func (x *UnregisterPhoneRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type UnregisterPhoneResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UnregisterPhoneResponse) Reset()         { *x = UnregisterPhoneResponse{} }
func (x *UnregisterPhoneResponse) String() string { return fmt.Sprintf("UnregisterPhoneResponse{Success:%v}", x.Success) }
func (x *UnregisterPhoneResponse) ProtoMessage()  {}

func (x *UnregisterPhoneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PhoneDataUpdate struct {
	Serial  string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Accel   *Vector3 `protobuf:"bytes,2,opt,name=accel,proto3" json:"accel,omitempty"`
	Gyro    *Vector3 `protobuf:"bytes,3,opt,name=gyro,proto3" json:"gyro,omitempty"`
	Buttons uint32   `protobuf:"varint,4,opt,name=buttons,proto3" json:"buttons,omitempty"`
	Battery int32    `protobuf:"varint,5,opt,name=battery,proto3" json:"battery,omitempty"`
	Seq     uint64   `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *PhoneDataUpdate) Reset()         { *x = PhoneDataUpdate{} }
func (x *PhoneDataUpdate) String() string { return fmt.Sprintf("PhoneDataUpdate{Serial:%q,Seq:%d}", x.Serial, x.Seq) }
func (x *PhoneDataUpdate) ProtoMessage()  {}

func (x *PhoneDataUpdate) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *PhoneDataUpdate) GetAccel() *Vector3 {
	if x != nil {
		return x.Accel
	}
	return nil
}

func (x *PhoneDataUpdate) GetGyro() *Vector3 {
	if x != nil {
		return x.Gyro
	}
	return nil
}

func (x *PhoneDataUpdate) GetButtons() uint32 {
	if x != nil {
		return x.Buttons
	}
	return 0
}

func (x *PhoneDataUpdate) GetBattery() int32 {
	if x != nil {
		return x.Battery
	}
	return 0
}

func (x *PhoneDataUpdate) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type PhoneCommand struct {
	Serial string `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`

	// Types that are assignable to Command:
	//
	//	*PhoneCommand_Led
	//	*PhoneCommand_Rumble
	Command isPhoneCommand_Command `protobuf_oneof:"command"`
}

func (x *PhoneCommand) Reset()         { *x = PhoneCommand{} }
func (x *PhoneCommand) String() string { return fmt.Sprintf("PhoneCommand{Serial:%q}", x.Serial) }
func (x *PhoneCommand) ProtoMessage()  {}

func (x *PhoneCommand) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *PhoneCommand) GetCommand() isPhoneCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *PhoneCommand) GetLed() *LedColor {
	if c, ok := x.GetCommand().(*PhoneCommand_Led); ok {
		return c.Led
	}
	return nil
}

func (x *PhoneCommand) GetRumble() *RumbleCommand {
	if c, ok := x.GetCommand().(*PhoneCommand_Rumble); ok {
		return c.Rumble
	}
	return nil
}

type isPhoneCommand_Command interface {
	isPhoneCommand_Command()
}

type PhoneCommand_Led struct {
	Led *LedColor `protobuf:"bytes,2,opt,name=led,proto3,oneof"`
}

type PhoneCommand_Rumble struct {
	Rumble *RumbleCommand `protobuf:"bytes,3,opt,name=rumble,proto3,oneof"`
}

func (*PhoneCommand_Led) isPhoneCommand_Command()    {}
func (*PhoneCommand_Rumble) isPhoneCommand_Command() {}

type Vector3 struct {
	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Vector3) Reset()         { *x = Vector3{} }
func (x *Vector3) String() string { return fmt.Sprintf("Vector3{X:%f,Y:%f,Z:%f}", x.X, x.Y, x.Z) }
func (x *Vector3) ProtoMessage()  {}

func (x *Vector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type LedColor struct {
	R uint32 `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`
	G uint32 `protobuf:"varint,2,opt,name=g,proto3" json:"g,omitempty"`
	B uint32 `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *LedColor) Reset()         { *x = LedColor{} }
func (x *LedColor) String() string { return fmt.Sprintf("LedColor{R:%d,G:%d,B:%d}", x.R, x.G, x.B) }
func (x *LedColor) ProtoMessage()  {}

func (x *LedColor) GetR() uint32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *LedColor) GetG() uint32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *LedColor) GetB() uint32 {
	if x != nil {
		return x.B
	}
	return 0
}

type RumbleCommand struct {
	Intensity uint32 `protobuf:"varint,1,opt,name=intensity,proto3" json:"intensity,omitempty"`
}

func (x *RumbleCommand) Reset()         { *x = RumbleCommand{} }
func (x *RumbleCommand) String() string { return fmt.Sprintf("RumbleCommand{Intensity:%d}", x.Intensity) }
func (x *RumbleCommand) ProtoMessage()  {}

func (x *RumbleCommand) GetIntensity() uint32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}
