// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: mobile_controller.proto
//
// NOTE: This file is generated during Docker build via buf.
// For local development, regenerate with:
//   cd proto && buf generate --template buf.gen.mobile.yaml

package mobile_controller

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// MobileControllerServiceClient is the client API for MobileControllerService.
type MobileControllerServiceClient interface {
	RegisterPhone(ctx context.Context, in *RegisterPhoneRequest, opts ...grpc.CallOption) (*RegisterPhoneResponse, error)
	UnregisterPhone(ctx context.Context, in *UnregisterPhoneRequest, opts ...grpc.CallOption) (*UnregisterPhoneResponse, error)
	StreamPhoneData(ctx context.Context, opts ...grpc.CallOption) (MobileControllerService_StreamPhoneDataClient, error)
}

type mobileControllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMobileControllerServiceClient(cc grpc.ClientConnInterface) MobileControllerServiceClient {
	return &mobileControllerServiceClient{cc}
}

func (c *mobileControllerServiceClient) RegisterPhone(ctx context.Context, in *RegisterPhoneRequest, opts ...grpc.CallOption) (*RegisterPhoneResponse, error) {
	out := new(RegisterPhoneResponse)
	err := c.cc.Invoke(ctx, "/joustmania.mobile_controller.MobileControllerService/RegisterPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileControllerServiceClient) UnregisterPhone(ctx context.Context, in *UnregisterPhoneRequest, opts ...grpc.CallOption) (*UnregisterPhoneResponse, error) {
	out := new(UnregisterPhoneResponse)
	err := c.cc.Invoke(ctx, "/joustmania.mobile_controller.MobileControllerService/UnregisterPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileControllerServiceClient) StreamPhoneData(ctx context.Context, opts ...grpc.CallOption) (MobileControllerService_StreamPhoneDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &MobileControllerService_ServiceDesc.Streams[0], "/joustmania.mobile_controller.MobileControllerService/StreamPhoneData", opts...)
	if err != nil {
		return nil, err
	}
	x := &mobileControllerServiceStreamPhoneDataClient{stream}
	return x, nil
}

type MobileControllerService_StreamPhoneDataClient interface {
	Send(*PhoneDataUpdate) error
	Recv() (*PhoneCommand, error)
	grpc.ClientStream
}

type mobileControllerServiceStreamPhoneDataClient struct {
	grpc.ClientStream
}

func (x *mobileControllerServiceStreamPhoneDataClient) Send(m *PhoneDataUpdate) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mobileControllerServiceStreamPhoneDataClient) Recv() (*PhoneCommand, error) {
	m := new(PhoneCommand)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MobileControllerServiceServer is the server API for MobileControllerService.
type MobileControllerServiceServer interface {
	RegisterPhone(context.Context, *RegisterPhoneRequest) (*RegisterPhoneResponse, error)
	UnregisterPhone(context.Context, *UnregisterPhoneRequest) (*UnregisterPhoneResponse, error)
	StreamPhoneData(MobileControllerService_StreamPhoneDataServer) error
	mustEmbedUnimplementedMobileControllerServiceServer()
}

// UnimplementedMobileControllerServiceServer should be embedded to have forward
// compatible implementations.
type UnimplementedMobileControllerServiceServer struct{}

func (UnimplementedMobileControllerServiceServer) RegisterPhone(context.Context, *RegisterPhoneRequest) (*RegisterPhoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPhone not implemented")
}

func (UnimplementedMobileControllerServiceServer) UnregisterPhone(context.Context, *UnregisterPhoneRequest) (*UnregisterPhoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterPhone not implemented")
}

func (UnimplementedMobileControllerServiceServer) StreamPhoneData(MobileControllerService_StreamPhoneDataServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPhoneData not implemented")
}

func (UnimplementedMobileControllerServiceServer) mustEmbedUnimplementedMobileControllerServiceServer() {}

// UnsafeMobileControllerServiceServer may be embedded to opt out of forward compatibility.
type UnsafeMobileControllerServiceServer interface {
	mustEmbedUnimplementedMobileControllerServiceServer()
}

type MobileControllerService_StreamPhoneDataServer interface {
	Send(*PhoneCommand) error
	Recv() (*PhoneDataUpdate, error)
	grpc.ServerStream
}

type mobileControllerServiceStreamPhoneDataServer struct {
	grpc.ServerStream
}

func (x *mobileControllerServiceStreamPhoneDataServer) Send(m *PhoneCommand) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mobileControllerServiceStreamPhoneDataServer) Recv() (*PhoneDataUpdate, error) {
	m := new(PhoneDataUpdate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func RegisterMobileControllerServiceServer(s grpc.ServiceRegistrar, srv MobileControllerServiceServer) {
	s.RegisterService(&MobileControllerService_ServiceDesc, srv)
}

func _MobileControllerService_RegisterPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileControllerServiceServer).RegisterPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/joustmania.mobile_controller.MobileControllerService/RegisterPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileControllerServiceServer).RegisterPhone(ctx, req.(*RegisterPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MobileControllerService_UnregisterPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileControllerServiceServer).UnregisterPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/joustmania.mobile_controller.MobileControllerService/UnregisterPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileControllerServiceServer).UnregisterPhone(ctx, req.(*UnregisterPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MobileControllerService_StreamPhoneData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MobileControllerServiceServer).StreamPhoneData(&mobileControllerServiceStreamPhoneDataServer{stream})
}

// MobileControllerService_ServiceDesc is the grpc.ServiceDesc for MobileControllerService service.
var MobileControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "joustmania.mobile_controller.MobileControllerService",
	HandlerType: (*MobileControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterPhone",
			Handler:    _MobileControllerService_RegisterPhone_Handler,
		},
		{
			MethodName: "UnregisterPhone",
			Handler:    _MobileControllerService_UnregisterPhone_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPhoneData",
			Handler:       _MobileControllerService_StreamPhoneData_Handler,
			ServerStreams:  true,
			ClientStreams:  true,
		},
	},
	Metadata: "mobile_controller.proto",
}
