#!/usr/bin/env bash
# Validate that committed Python proto stubs match a fresh generation.
#
# Why this gate exists (#904):
#   The committed proto/*_pb2.py / *_pb2_grpc.py stubs are the source of truth
#   for unit tests, while service *images* regenerate stubs at build time. If the
#   two drift, units can assert against symbols that do not exist in production
#   (e.g. GAME_EFFECT_WIN_FLASH in #899): units pass, the real service crashes
#   with AttributeError. This gate must fail on ANY committed/fresh divergence.
#
# Root-cause gap this rewrite closes (#904):
#   The previous gate ran `git diff --exit-code -- 'proto/*.py'`. `git diff` only
#   compares TRACKED files, so it was blind to:
#     - untracked generated stubs (a newly added .proto whose stub was never
#       committed, or a committed stub deleted from tracking) — regen recreates
#       them as untracked and `git diff` reports nothing -> false green
#     - it also gave weak diagnostics and a non-recursive glob.
#   We now use `git status --porcelain` over the generated-stub set, which
#   surfaces modified, untracked AND deleted files alike, plus an explicit
#   "every .proto has its stubs" completeness check.
#
# Toolchain invariant (must stay true or this gate is meaningless):
#   The generation here runs inside joustmania/ci-proto:latest, which installs
#   grpcio-tools/protobuf via the repo's uv.lock (same pins the service images
#   use). If the container toolchain ever diverges from the service-image
#   toolchain, generated bytes can differ and the gate would compare against the
#   wrong baseline. Keep both driven by uv.lock. (proto/pyproject.toml pins
#   protobuf>=6.33.5 / grpcio-tools>=1.70.0; uv.lock resolves the exact build.)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$PROJECT_ROOT"

echo "Validating proto generation..."

# Patterns for the generated Python stubs we compare. Kept in one place so the
# regen, the completeness check and the drift check all agree.
STUB_GLOBS=('proto/*_pb2.py' 'proto/*_pb2_grpc.py')

# --- Regenerate inside the pinned CI container -------------------------------
docker run --rm \
    -v "$PROJECT_ROOT:/workspace" \
    -w /workspace \
    joustmania/ci-proto:latest \
    bash proto/generate_proto.sh

# --- Completeness check: every committed .proto must have its stubs ----------
# Catches the "new .proto added, stub never committed" case directly (regen
# would create untracked stubs; this turns that into an explicit error).
missing=0
for proto in proto/*.proto; do
    base="$(basename "$proto" .proto)"
    for suffix in _pb2.py _pb2_grpc.py; do
        stub="proto/${base}${suffix}"
        if [[ ! -f "$stub" ]]; then
            echo "❌ Expected generated stub is missing: $stub (from $proto)"
            missing=1
        fi
    done
done
if [[ "$missing" -ne 0 ]]; then
    echo "❌ Proto stubs incomplete! Run 'make protos' and commit the new stubs."
    exit 1
fi

# --- Drift check: porcelain status over the generated-stub set ---------------
# `git status --porcelain` reports modified, untracked and deleted paths, so a
# regenerated-but-uncommitted stub (untracked) is no longer invisible the way it
# was under `git diff --exit-code`.
status="$(git status --porcelain -- "${STUB_GLOBS[@]}")"
if [[ -n "$status" ]]; then
    echo "❌ Proto files are out of sync! Run 'make protos' and commit changes."
    echo "Divergent generated stubs:"
    echo "$status"
    echo "--- diff (tracked files) ---"
    # Show a content diff for tracked files to aid debugging; untracked files are
    # already named in the porcelain status above.
    git diff -- "${STUB_GLOBS[@]}" || true
    exit 1
fi

echo "✅ Proto files validated!"
