# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mobile_controller.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mobile_controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17mobile_controller.proto\x12\x1cjoustmania.mobile_controller\"$\n\x14RegisterPhoneRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"8\n\x15RegisterPhoneResponse\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"(\n\x16UnregisterPhoneRequest\x12\x0e\n\x06serial\x18\x01 \x01(\t\"*\n\x17UnregisterPhoneResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\xbb\x01\n\x0fPhoneDataUpdate\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\x34\n\x05\x61\x63\x63\x65l\x18\x02 \x01(\x0b\x32%.joustmania.mobile_controller.Vector3\x12\x33\n\x04gyro\x18\x03 \x01(\x0b\x32%.joustmania.mobile_controller.Vector3\x12\x0f\n\x07\x62uttons\x18\x04 \x01(\r\x12\x0f\n\x07\x62\x61ttery\x18\x05 \x01(\x05\x12\x0b\n\x03seq\x18\x06 \x01(\x04\"\x9f\x01\n\x0cPhoneCommand\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\x35\n\x03led\x18\x02 \x01(\x0b\x32&.joustmania.mobile_controller.LedColorH\x00\x12=\n\x06rumble\x18\x03 \x01(\x0b\x32+.joustmania.mobile_controller.RumbleCommandH\x00\x42\t\n\x07\x63ommand\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"+\n\x08LedColor\x12\t\n\x01r\x18\x01 \x01(\r\x12\t\n\x01g\x18\x02 \x01(\r\x12\t\n\x01\x62\x18\x03 \x01(\r\"\"\n\rRumbleCommand\x12\x11\n\tintensity\x18\x01 \x01(\r2\x85\x03\n\x17MobileControllerService\x12x\n\rRegisterPhone\x12\x32.joustmania.mobile_controller.RegisterPhoneRequest\x1a\x33.joustmania.mobile_controller.RegisterPhoneResponse\x12~\n\x0fUnregisterPhone\x12\x34.joustmania.mobile_controller.UnregisterPhoneRequest\x1a\x35.joustmania.mobile_controller.UnregisterPhoneResponse\x12p\n\x0fStreamPhoneData\x12-.joustmania.mobile_controller.PhoneDataUpdate\x1a*.joustmania.mobile_controller.PhoneCommand(\x01\x30\x01\x42;Z9github.com/joustmania/connect-proxy/gen/mobile_controllerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mobile_controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/joustmania/connect-proxy/gen/mobile_controller'
  _globals['_REGISTERPHONEREQUEST']._serialized_start=57
  _globals['_REGISTERPHONEREQUEST']._serialized_end=93
  _globals['_REGISTERPHONERESPONSE']._serialized_start=95
  _globals['_REGISTERPHONERESPONSE']._serialized_end=151
  _globals['_UNREGISTERPHONEREQUEST']._serialized_start=153
  _globals['_UNREGISTERPHONEREQUEST']._serialized_end=193
  _globals['_UNREGISTERPHONERESPONSE']._serialized_start=195
  _globals['_UNREGISTERPHONERESPONSE']._serialized_end=237
  _globals['_PHONEDATAUPDATE']._serialized_start=240
  _globals['_PHONEDATAUPDATE']._serialized_end=427
  _globals['_PHONECOMMAND']._serialized_start=430
  _globals['_PHONECOMMAND']._serialized_end=589
  _globals['_VECTOR3']._serialized_start=591
  _globals['_VECTOR3']._serialized_end=633
  _globals['_LEDCOLOR']._serialized_start=635
  _globals['_LEDCOLOR']._serialized_end=678
  _globals['_RUMBLECOMMAND']._serialized_start=680
  _globals['_RUMBLECOMMAND']._serialized_end=714
  _globals['_MOBILECONTROLLERSERVICE']._serialized_start=717
  _globals['_MOBILECONTROLLERSERVICE']._serialized_end=1106
# @@protoc_insertion_point(module_scope)
