# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import mobile_controller_pb2 as mobile__controller__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mobile_controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MobileControllerServiceStub(object):
    """MobileControllerService — gRPC interface between mobile-gateway and controller-manager.
    Runs on controller-manager port 50063.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterPhone = channel.unary_unary(
                '/joustmania.mobile_controller.MobileControllerService/RegisterPhone',
                request_serializer=mobile__controller__pb2.RegisterPhoneRequest.SerializeToString,
                response_deserializer=mobile__controller__pb2.RegisterPhoneResponse.FromString,
                _registered_method=True)
        self.UnregisterPhone = channel.unary_unary(
                '/joustmania.mobile_controller.MobileControllerService/UnregisterPhone',
                request_serializer=mobile__controller__pb2.UnregisterPhoneRequest.SerializeToString,
                response_deserializer=mobile__controller__pb2.UnregisterPhoneResponse.FromString,
                _registered_method=True)
        self.StreamPhoneData = channel.stream_stream(
                '/joustmania.mobile_controller.MobileControllerService/StreamPhoneData',
                request_serializer=mobile__controller__pb2.PhoneDataUpdate.SerializeToString,
                response_deserializer=mobile__controller__pb2.PhoneCommand.FromString,
                _registered_method=True)


class MobileControllerServiceServicer(object):
    """MobileControllerService — gRPC interface between mobile-gateway and controller-manager.
    Runs on controller-manager port 50063.
    """

    def RegisterPhone(self, request, context):
        """Register a phone as a controller. Returns assigned serial.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterPhone(self, request, context):
        """Unregister a phone controller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPhoneData(self, request_iterator, context):
        """Bidirectional stream: gateway pushes sensor data, receives LED/rumble commands.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MobileControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterPhone': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPhone,
                    request_deserializer=mobile__controller__pb2.RegisterPhoneRequest.FromString,
                    response_serializer=mobile__controller__pb2.RegisterPhoneResponse.SerializeToString,
            ),
            'UnregisterPhone': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterPhone,
                    request_deserializer=mobile__controller__pb2.UnregisterPhoneRequest.FromString,
                    response_serializer=mobile__controller__pb2.UnregisterPhoneResponse.SerializeToString,
            ),
            'StreamPhoneData': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPhoneData,
                    request_deserializer=mobile__controller__pb2.PhoneDataUpdate.FromString,
                    response_serializer=mobile__controller__pb2.PhoneCommand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'joustmania.mobile_controller.MobileControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('joustmania.mobile_controller.MobileControllerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MobileControllerService(object):
    """MobileControllerService — gRPC interface between mobile-gateway and controller-manager.
    Runs on controller-manager port 50063.
    """

    @staticmethod
    def RegisterPhone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.mobile_controller.MobileControllerService/RegisterPhone',
            mobile__controller__pb2.RegisterPhoneRequest.SerializeToString,
            mobile__controller__pb2.RegisterPhoneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterPhone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.mobile_controller.MobileControllerService/UnregisterPhone',
            mobile__controller__pb2.UnregisterPhoneRequest.SerializeToString,
            mobile__controller__pb2.UnregisterPhoneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPhoneData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/joustmania.mobile_controller.MobileControllerService/StreamPhoneData',
            mobile__controller__pb2.PhoneDataUpdate.SerializeToString,
            mobile__controller__pb2.PhoneCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
