# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: psmove_hid.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'psmove_hid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10psmove_hid.proto\x12\x15joustmania.psmove_hid\"\x1a\n\x18GetUSBControllersRequest\"4\n\rUSBController\x12\x13\n\x0b\x64\x65vice_path\x18\x01 \x01(\t\x12\x0e\n\x06serial\x18\x02 \x01(\t\"V\n\x19GetUSBControllersResponse\x12\x39\n\x0b\x63ontrollers\x18\x01 \x03(\x0b\x32$.joustmania.psmove_hid.USBController\"U\n\x15PairControllerRequest\x12\x13\n\x0b\x64\x65vice_path\x18\x01 \x01(\t\x12\x0e\n\x06serial\x18\x02 \x01(\t\x12\x17\n\x0f\x61\x64\x61pter_address\x18\x03 \x01(\t\"X\n\x16PairControllerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0e\x61lready_paired\x18\x02 \x01(\x08\x12\x15\n\rprevious_host\x18\x03 \x01(\t2\xf7\x01\n\x0ePairingService\x12v\n\x11GetUSBControllers\x12/.joustmania.psmove_hid.GetUSBControllersRequest\x1a\x30.joustmania.psmove_hid.GetUSBControllersResponse\x12m\n\x0ePairController\x12,.joustmania.psmove_hid.PairControllerRequest\x1a-.joustmania.psmove_hid.PairControllerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'psmove_hid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSBCONTROLLERSREQUEST']._serialized_start=43
  _globals['_GETUSBCONTROLLERSREQUEST']._serialized_end=69
  _globals['_USBCONTROLLER']._serialized_start=71
  _globals['_USBCONTROLLER']._serialized_end=123
  _globals['_GETUSBCONTROLLERSRESPONSE']._serialized_start=125
  _globals['_GETUSBCONTROLLERSRESPONSE']._serialized_end=211
  _globals['_PAIRCONTROLLERREQUEST']._serialized_start=213
  _globals['_PAIRCONTROLLERREQUEST']._serialized_end=298
  _globals['_PAIRCONTROLLERRESPONSE']._serialized_start=300
  _globals['_PAIRCONTROLLERRESPONSE']._serialized_end=388
  _globals['_PAIRINGSERVICE']._serialized_start=391
  _globals['_PAIRINGSERVICE']._serialized_end=638
# @@protoc_insertion_point(module_scope)
