apiVersion: 1

datasources:
  - name: Prometheus (Direct)
    uid: prometheus-direct
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
    jsonData:
      timeInterval: "500ms"
